import Sidebar from '@/components/Sidebar';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='flex bg-gray-800 text-gray-300'>
        <Sidebar />
        <main className='md:absolute md:ml-[20vw]'>{children}</main>
      </body>
    </html>
  );
}
